workflows:
  unified-workflow:
    name: Unified Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest # <-- set to specific version e.g. 14.3, 15.0 to avoid unexpected updates.
      cocoapods: default
    scripts:
      - name: Analyze and test
        script: |
          cd frontend
          flutter packages pub get
          flutter analyze
          flutter test || true
      - name: Android build
        script: |
          cd frontend
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/frontend/android/local.properties"
          flutter build appbundle --release
      - name: iOS build
        script: |
          cd frontend
          find . -name "Podfile" -execdir pod install \;
          flutter build ios --simulator
      - name: Web build
        script: |
          cd frontend
          flutter build web --release
          cd build/web
          7z a -r ../web.zip ./*
    artifacts:
      - frontend/build/**/outputs/**/*.aab
      - frontend/build/**/outputs/**/mapping.txt
      - frontend/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - frontend/build/web.zip
      - frontend/flutter_drive.log
