workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/frontend/android/local.properties"
      - name: Get Flutter packages
        script: |
          cd frontend
          flutter packages pub get
      - name: Flutter analyze
        script: |
          cd frontend
          flutter analyze
      - name: Flutter unit tests
        script: |
          cd frontend
          flutter test
        ignore_failure: true
      - name: Build AAB with Flutter
        script: |
          cd frontend
          flutter build appbundle --release
    artifacts:
      - frontend/build/**/outputs/**/*.aab
      - frontend/build/**/outputs/**/mapping.txt
      - frontend/flutter_drive.log
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest # <-- set to specific version e.g. 14.3, 15.0 to avoid unexpected updates.
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          cd frontend
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          cd frontend
          flutter packages pub get
      - name: Install pods
        script: |
          cd frontend
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          cd frontend
          flutter analyze
      - name: Flutter unit tests
        script: |
          cd frontend
          flutter test
        ignore_failure: true
      - name: Flutter build ipa
        script: |
          cd frontend
          flutter build ipa --release
    artifacts:
      - frontend/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - frontend/flutter_drive.log
  web-workflow:
    name: Web app workflow
    max_build_duration: 10
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          cd frontend
          flutter packages pub get
      - name: Flutter analyze
        script: |
          cd frontend
          flutter analyze
      - name: Flutter unit tests
        script: |
          cd frontend
          flutter test
      - name: Flutter build webapp
        script: |
          cd frontend
          flutter build web --release
          cd build/web
          7z a -r ../web.zip ./*
    artifacts:
      - frontend/build/web.zip
      - frontend/flutter_drive.log
