name: firstday
description: "An onboarding app and training platform for your employees."
publish_to: "none"
version: 0.1.0

repository: https://github.com/abianche/firstday
issue_tracker: https://github.com/abianche/firstday/issues

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  meta: ^1.15.0
  package_info_plus: ^8.1.2
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
